### ISSUE TITLE
No rethrows or warnings for exceptions inside definitionFn of createStream

### ISSUE THREAD

**Issue by pH200** [staltz/cycle#107]
```js
let vtree$ = Cycle.createStream(interaction$ => {
  return Rx.Observable.throw(new Error('The Error'));
});
let interaction$ = Cycle.createStream(vtree$ =>
  Cycle.render(vtree$, '#app-container').interaction$
);
interaction$.inject(vtree$).inject(interaction$);
```

The above code will get you nothing on the screen, nor on the console. You will get no indication of how it goes wrong. This is frustrating when the error happens really deep in the real application.

Here's a more real-world-like example:

```js
let vtree$ = Cycle.createStream(interaction$ => {
  return Rx.Observable.defer(() => {
    let obj = JSON.parse('{"foo":invalid json}');
    return Rx.Observable.just(obj);
  }).map(obj => h('.root', obj.foo));
});
```

**Comment by staltz** [comment]
Hi @pH200 , because Streams are Observables, they have the same error handling solution: subscribing for errors. If you don't catch errors happening internally, then at least you should have a top-level catch for all errors, which would be `subscribeOnError` on vtree$ and also on interaction$. [See these docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/subscribeonerror.md).

There is really no point in building this because not all `foo$` in your app are Streams, some of them can be pure Observables, and Observables already have error handling solutions.

**Comment by pH200** [comment]
Hi, thanks for the nice explanation.

For Observables, if we don't provide onError to subscribe and get an exception, then it fails immediately. But in Cycle there is no "subscribe" so it seems a bit weird to me.

I'll see if I can come up with another solution. But before that, I think I'll make a wrapper for createStream for this issue.

**Comment by staltz** [comment]
> But in Cycle there is no "subscribe" so it seems a bit weird to me.

@pH200 Yes there is. You can subscribe to any stream, and Streams are pretty much everything in Cycle.
