### ISSUE TITLE
Thoughts on Web Components?

### ISSUE THREAD

**Issue by tauren** [staltz/cycle#70]
I've been inspired after reading http://futurice.com/blog/reactive-mvc-and-the-virtual-dom, as the description of an MVI framework comes the closest to describing framework concepts that have been bouncing around in my head, but were not concrete enough to describe or implement. This prompted me to begin exploring Cycle, Mercury, Mithril, and Flux/React, hoping to find a framework that I can get behind. 

I also believe Web Components will play a big role in the future, but there is a fundamental difference between them and the reactive solutions. This article http://futurice.com/blog/combining-react-flux-and-web-components discusses this in detail.

My ideal framework would:

1. Embrace MVI concepts
2. Utilize virtual-dom
3. Utilize rxjs
4. Be isomorphic (run in client or server)
5. Embraces a future of Web Components
6. Simplify code
7. Utilize dependency injection, improve testability
8. Support external templates/markup

It seems Cycle comes the closest to this, being based on MVI and utilizing rxjs and virtual-dom and supporting isomorphic use. However, I'm unclear how Web Components will play into things. I realize that a web component is just an html entity, so it can be rendered with the virtual dom. But the shadow dom would be managed by the web component, not Cycle. What if virtual-dom chooses to remove the web component node and add it back again, losing internal state of the web component? Has any thought gone into how to support Web Components with Cycle?

I took a look at the Cycle TodoMVC sample, and the implementation is quite involved. It appears to need far more code, and more complex code, than many of the other TodoMVC apps. I assume that as an application becomes bigger, the benefit of using rxjs gets more significant. But after seeing rxjs examples that show how complex logic can be boiled down to 4 lines of code, I was hoping to see a very simple implementation.

Testability is extremely important, and dependency injection helps tremendously as shown by frameworks such as Angular. I don't yet know enough about Cycle, but I'm assuming it is fairly strong in this regard.

My last point isn't a top priority, and I'm willing to let it go. But I do find it tedious to "code" my HTML instead of using markup. Yet, I'm not a fan of JSX either. It seems like there must be some way to separate the markup from the code, but still attach logic and behavior to the markup. Angular, handlebars, etc. have ways to accomplish this.

Would love to hear other's thoughts on this.

**Comment by staltz** [comment]
Hi @tauren, I hear your concerns. Web Components are a big priority in Cycle, and custom elements (a feature in the framework) were built with an API such that from the interface perspective, using a Cycle custom element looks identical to using a web component.

Have you seen these?
https://github.com/staltz/cycle/blob/master/examples/custom-element/custom-element.js
https://gist.github.com/staltz/2f0704b1ecadc42fb0ab

Web Components are out-of-the-box supported by virtual-dom, therefore also for Cycle.

> What if virtual-dom chooses to remove the web component node and add it back again, losing internal state of the web component?

That would be the same as removing the web component with raw DOM handlers, and adding it again with DOM handling. virtual-dom doesn't "add and remove" by mistake or internally. Don't worry, using a web component works just like using any other div. That is precisely the idea of web components.

> I took a look at the Cycle TodoMVC sample, and the implementation is quite involved. It appears to need far more code, and more complex code, than many of the other TodoMVC apps.

Agreed and Cycle TodoMVC will be rewritten to use custom elements. I haven't done that yet because other things are priority above examples and docs. As said in the README, Cycle isn't ready yet. No point in documenting it thoroughly before it's ready. And by ready I mean "major framework decisions and general app development philosophy and guidelines are stable".

**Comment by staltz** [comment]
Also, these discussions: https://gitter.im/staltz/cycle/archives/2015/01/10

**Comment by qur2** [comment]
[Although it doesn't help the discussion] I'm very pleased to see components in Cycle, with a very similar intent to web components.

**Comment by staltz** [comment]
I'll close this unless @tauren wants to continue the discussion.

**Comment by tauren** [comment]
I have no problem with you closing this as you've address most of my questions in your previous reply. I'm glad to hear that you are taking web components into consideration.

**Comment by rofrol** [comment]
Probably better to link to discussion https://gitter.im/cyclejs/cycle-core/archives/2015/01/10 than https://gitter.im/staltz/cycle/archives/2015/01/10
