### ISSUE TITLE
Widget and custom element bugs on v0.14.4

### ISSUE THREAD

**Issue by staltz** [staltz/cycle#77]
Visit http://staltz.com/todomvc-cycle/ and put a breakpoint inside the DOMUser's renderEvery, for instance before the diff and patch line. Every time the user toggles a todo item, the whole list of todos will be rerendered (deleted and added), which should definitely not happen since with the custom elements approach, a toggle inside one custom element shouldn't affect others.

Adding `this.key = vtree.key` into the constructor of the custom element fixes the issue, but introduces others: some elements stop emitting events, random glitches, etc.

**Comment by staltz** [comment]
I'll just dump some discoveries as "note to self":

Every time a parent vtree$ emits a vtree containing some `h('my-customelem', {prop1: 'a'})`, the Properties DataFlowNode of `my-customelem`'s implementation will emit 'a' on `prop1$`. This is a problem because I was assuming virtual-dom does diffing on the Widgets, but it doesn't, it calls widget.update() every time we use `h('my-customelem', {prop1: 'a'})`. We need to add a way of not emitting consecutive duplicatives into Properties.prop1$, maybe with a `distinctUntilChanged()` somewhere. For instance, if we use `Properties.get('prop1$').distinctUntilChanged()` inside a custom element's Model, several of the glitches are fixed. (unfortunately not all).

**Comment by staltz** [comment]
Idea: make a special version of InputProxy just for custom element properties. (maybe "PropsInputProxy"?). Inside the `get()`, return `theSubject.distinctUntilChanged()`.

**Comment by cgeorg** [comment]
Is widget the right thing to use for custom elements?  We are pre-processing the vtree - can we just drop in the actual vtree from the custom element in its place?  I will need to dig into the code to know if this makes sense at all, but it looks like Widgets in the virtual-dom sense are for elements that need stricter control over their DOM?

(sparse) [widget docs](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md) for reference.

The distinctUntilChanged seems solid, but custom elements may need to actually emit duplicate events so that seems like it could also cause problems.  If we have to stick with Widgets we might be able to hook into the lifecycle to just skip the first event if it turns out we're an update and not an init.

**Comment by staltz** [comment]
Actually distinctUntilChanged is completely safe. Because under virtual-dom's diff, a real DOM element's property is only _updated_ if the vtree's property has _changed_ (that's the point in diffing). Just think in HTML: if you make `<img src="something">` and then `<img src="something">`, they should be completely identical as far as the input is concerned. distinctUntilChanged will only be applied on **input** properties. Output events are still allowed to emit whatever, including consecutive duplicates.

> Is widget the right thing to use for custom elements? We are pre-processing the vtree - can we just drop in the actual vtree from the custom element in its place?

We could, but I think using Widgets simplifies the implementation. The custom element needs to have internally an Intent, and Intents require a DOMUser. So custom elements produce DOM elements, not just vtrees. And Widget is the appropriate tool for wrapping anything that produces DOM elements which we want to use in the context of a virtual DOM.

**Comment by staltz** [comment]
Fixed in [v0.15.0](https://github.com/staltz/cycle/releases/tag/v0.15.0)
