### ISSUE TITLE
Capital case of Model, View, Intent variables

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle#81]
```javascript
function createModel(definitionFn) {
  var model = new DataFlowNode(definitionFn);
  ...
  return model; // here is lower case
}
```

```javascript
let Model = Cycle.createModel(Intent => // here is capital case
  ({name$: Intent.get('changeName$').startWith('')})
);
```

If `model` is not a class or pseudo-class (like `React`), why is it capitalized? If it's capitalized in app code, why it's not capitalized in library code? I'm not so hair-splitting person, but this makes me think I miss something every time I look at examples.

**Comment by staltz** [comment]
Because Cycle is more functional than object oriented, classes are not that used. The reasoning behind this was to have a convention to know the types of variables. "Foo" would mean an instance of a DataFlowNode, while "foo$" would mean an observable, and "foo" would be a value emitted by "foo$".

That said, I might change the convention back to lowercase "model". That's because Cycle is unfinished and pre-v1.0 I want to experiment with ideas and kill them as fast as possible. I'm currently reimplementing it in ES6, and noticed that users might want to subclass DataFlowNode. In that case it would make sense that subclasses are first-character-uppercase. So, you might be right, and I probably will change the convention back to lowercase for models, views, intents.

**Comment by ivan-kleshnin** [comment]
Ah, it makes sense to me now. I'd put my vote for sticking with common JS conventions and lowercasing if it matters. I have one more similar question:

```
Intent.get("changeName$") // "getter" style
User.event$(".field", "input") // "property" style
```

Could you explain the reason behind this visual asymmetry as well? Thanks!

**Comment by staltz** [comment]
`Intent.get("changeName$")` there is one dollar sign here, which mean `changeName$` is an observable. So we read it as: **get** the **changeName** stream from **Intent**.

`User.event$('.field', 'input')` here, neither `.field` nor 'input' are observables, so `event$` means "get the event stream...". So we read it as **getEventStream** made of **input** events from **.field** from the **User**.

In the end, they are two different things. The first is a ready observable, the second you are building an observable out of primitives.

**Comment by ivan-kleshnin** [comment]
Ok, I think it's clear enough, thanks!
