### ISSUE TITLE
Provide example of View returning custom observables

### ISSUE THREAD

**Issue by ivan-kleshnin** [staltz/cycle#83]
Now all Views return object with `vtree$` observable. This is one is required. I suppose there can be more custom keys (observables) but it's unclear for me how can I access and use them from outside.

If there is some example or discussion I missed, please drop a link.

**Comment by staltz** [comment]
@ivan-kleshnin a View is a DataFlowNode so it can do anything a DataFlowNode can. In other words, "just do it".

```javascript
var Model = Cycle.createModel(View =>
  ({num$: View.get('everySecond$').map(() => Math.random()).startWith(1)})
});

var View = Cycle.createView(Model =>
  ({
    vtree$: Model.get('num$').map(name =>
      h('div', [
        h('label', 'Name:'),
        h('input.field', {attributes: {type: 'text'}}),
        h('h1.header', 'Hello ' + name)
      ])
    ),
    everySecond$: Rx.Observable.interval(1000)
  })
);

View.inject(Model).inject(View);
```

That said, this is probably an anti-pattern since Views should do just one thing which is define how the app should look. Any other observable is probably a state stream or some event stream. These should probably live in a Model, or exported as an event stream in a custom element.

**Comment by ivan-kleshnin** [comment]
I stuck with that because DOMUser seems to doesn't expose that observables.

```html
<body>
  <main></main>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/2.4.3/rx.all.js"></script>
  <script src="https://rawgit.com/staltz/cycle/master/dist/cycle.min.js"></script>
  <script>
    var Model = Cycle.createModel(function(DOM) {
      return {
        num$: DOM.get("everySecond$").map(function() { return Math.random().startWith(1) })
      };
    });

    var View = Cycle.createView(function(Model) {
      return {
        vtree$: Model.get("num$").map(function(name) {
          h("div", [
            h("label", "Name:"),
            h("input.field", {attributes: {type: "text"}}),
            h("h1.header", "Hello " + name)
          ]);
        }),

        everySecond$: Rx.Observable.interval(1000)
      };
    });

    var DOM = Cycle.createDOMUser("main");

    Model.inject(DOM);
    View.inject(Model);
    DOM.inject(View);
  </script>
</body>
```

**CycleInterfaceError: Model expects an input to have the required property everySecond$**

**Comment by staltz** [comment]
Why are you trying to make it pass through the DOMUser? I believe you should either do typical Model-View-User-Intent (the Intent is missing here), or do what I mentioned earlier, where the Model gets the View injected.

```javascript
User.inject(View).inject(Model).inject(View);
```

**Comment by ivan-kleshnin** [comment]
I've got the idea that all DataFlowNodes are equal and I shouldn't be afraid of swapping them. My first question still feels unanswered, or perhaps I expressed it not clear enough. 
Let me answer it myself and please fix if I'm wrong.

There is no obvious sense to return something other than `vtree$` from View right now *if View will be consumed by DOM only*. But you keep same API to keep symmetry with other DataFlowNodes.

I mean if only `vtree$` will ever be returned from View, we could simplify return value by removing object wrapper. Tthat would require additional NodeType. As we already have `DataSinkNode` and `DataSourceNode` it's fair to at least consider the alternative of such `ViewNode`. 
I'm not competent enough about subject to judge benefits and drawbacks.

**Comment by staltz** [comment]
> There is no obvious sense to return something other than vtree$ from View right now if View will be consumed by DOM only.

Yes, correct.

> I mean if only vtree$ will ever be returned from View, we could simplify return value by removing object wrapper.

I have thought about it, but I prefer to keep some boilerplate which is consistent with the rest of the framework and which also teaches the programmer how things work. I like this API guideline, because there is a tradeoff between boilerplate and magic. Too little boilerplate and the framework feels like magic, but you are very productive. Too much boilerplate and you have a lot of visibility into how everything works (no magic), but you aren't productive enough since there is a lot of writing to do. I prefer to have a balance between these two, but when I need to choose, I prefer boilerplate instead of magic.

Also, it is actually very easy to make this wrapper function. If anyone feels like reducing boilerplate, Cycle framework doesn't stop you from doing these helpers and wrappers.

`DataFlowSource` and `DataFlowSink` are a different subject. They are special cases of `DataFlowNode`, but still maintain the same interface API. The wrapper View you mentioned would have a different interface API.

**Comment by ivan-kleshnin** [comment]
Fair and clear. Thanks!
