### ISSUE TITLE
Transducers and DataFlowNode

### ISSUE THREAD

**Issue by markmarijnissen** [staltz/cycle#85]
I'm reading a lot about functional reactive programming.

What I got from reading the Cycle source code is that everything is build around a "DataFlowNode".

A DataFlowNode basically takes an input, applies a transformation, and then has an output. You can have a sink for output (i.e. GUI) and a source for input (i.e. API call). 

What I understood from Transducers is that they are a method to abstract the transformation from the actual stream (i.e. input/output).

Wouldn't it be more elegant to use Transducers instead of DataFlowNodes? Or: What is the difference bteween a Transducer and a DataFlowNode?

**Comment by jeffbski** [comment]
From my understanding of transducers, I believe they are synchronous operations, you can compose any number of map, filter, and other fn's but each of those is synchronous. Now of course the transducer can be applied to a push or pull async stream, but when it processes the events, it does it synchronously.

If you need to do anything asynchronously in your transform fn, then I don't believe you could use transducers. 

If the operations you are performing are all synchronous, then transducers would be a a great fit.

I'm only roughly familiar with cycle, so I can't comment as to which parts might be async or sync. I imagine the view parts could be sync and working with the data might be async??

**Comment by staltz** [comment]
Hi @markmarijnissen,

Have you read https://github.com/staltz/cycle/blob/master/docs/data-flow-nodes.md ?

Hence 
> A DataFlowNode basically takes an input, applies a transformation, and then has an output. You can have a sink for output (i.e. GUI) and a source for input (i.e. API call).

... Is actually: a DataFlowNode creates a proxy for the input, applies a transformation on that proxy, produces the output. Then later it receives the actual input, making the proxy imitate the input.

Basically a DataFlowNode is an better interface to an Rx technique to deal with circular dependent streams. A DataFlowNode wraps a Rx.Subject and makes it easy to express circular dependencies.

I believe the equivalent to Transducer in Rx is simply an Rx operator. That's not really what a DataFlowNode is.

**Comment by markmarijnissen** [comment]
Ah, yes, the [RxJS Subject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/subjects.md) seems the correct thing.

The improvement of a DataFlowNode is that it can handle multiple streams? 

If using an RxSubject, you need to merge inputs (and then filter them inside again) - which would be a little clumsy. Correct?

**Comment by jeffbski** [comment]
FYI. Just to clarify transducers are a concept of composable transform operations (map, filter, ...) which can be universally applied to any sort of stream, observable, iterable, etc. So rather than recreate that functionality for every sort of collection or stream, you can just use transducers on all of them. No more reimplementing all this functionality. Rxjs added the capability to use transducers so that it could accept them.

One JS version of transducers which I like is here https://github.com/transduce/transduce and it includes some more links to other docs. 

Rich Hickey gave a great talk on transducers at strange loop last year https://www.youtube.com/watch?v=6mTbuzafcII

**Comment by markmarijnissen** [comment]
Exactly.




Since transducers are independent of input and output, they solve the problem  of circular dependencies.




Instead of calling inject, you would do like this:




1. Create RxSubject Model.

2. Add the Model (a transducer)

3. Add the View (a transducer)

4. Add the Intent (a transducer)

5. Subscribe to itself.




As alternative to transducers you could use normal functions. Then add them with flatMap.




You're working with a single stream instead of multiple input/output streams, but this is easily solved using "merge" to merge multiple inputs and "filter" to create multiple outputs.




So I wonder: what is the added benefit of a DataFlowNode? Avoiding merge/filter? Performance perhaps?



—

**Comment by rovqapint** [comment]
You can use RxJS with Transducers - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/transducers.md

Maybe mixed solution(DataFlowNode with Transducers) can be reviewed also .

**Comment by ivan-kleshnin** [comment]
@rovqapint, right, `transduce` is an operator from RxJS set, just like @staltz mentioned. 

@jeffbski and @markmarijnissen believe there is possibility to replace each (or some) `DataFlowNode` with transducers. I don't get how, because `DataFlowNode` accepts and returns map of `Observables`. 
I think `Observable` concept is one level higher than `transducer`.  `DataFlowNode` is two level higher.

So the proposition of this issue it blurry to me.

**Comment by staltz** [comment]
![screen shot 2015-03-25 at 11 45 25](https://cloud.githubusercontent.com/assets/90512/6821941/7ffa2f7c-d2e4-11e4-94bc-0a461258d3eb.png)

**Comment by jeffbski** [comment]
@ivan-kleshnin and @staltz thanks for the clarifications. I have a better understanding now.

**Comment by markmarijnissen** [comment]
Thanks! I understand where I was confused now.

However, the underlying point that was bothering me was the unnecessary abstraction of bundling multiple streams into an object called DataFlowNode.

I see you've refactored the code to only use streams now, with the ability to inject one or more streams into the main stream. Awesome!!!!

**Comment by staltz** [comment]
I'll close this issue unless anyone wants to continue this discussion.
