### ISSUE TITLE
Cycle Streams

### ISSUE THREAD

**Issue by staltz** [staltz/cycle#99]
- [x] `Cycle.createStream(definitionFn)`
- [x] `Cycle.render(vtree$, container)`
- [x] Custom elements
- [x] Adapt all examples to Stream-style
- [x] Remove DataFlowNode, Source, Sink, DOMUser, Model, View, Intent
- [x] Change `getInteractions$()` to `interactions$`
- [x] Use Map for CustomElementsRegistry
- [x] Fix tests
- [x] Debug 'many' bad performance
- [x] Fix docs

This will likely affect Cycle entirely. We might need to deprecate DataFlowNode/Source/Sink.

Introduce a new primitive: Stream, which extends Rx.Observable and implements "Injectable", allowing circular dependencies of Rx.Observables without surfacing Subjects.

```javascript
let first$ = Cycle.createStream(second$ =>
  second$.delay(1000).startWith(0).map(x => 'ping')
);

let second$ = Cycle.createStream(first$ =>
  first$.delay(200).map(x => 'pong')
);

function printIt(x) { console.log(x); }
first$.subscribe(printIt);
second$.subscribe(printIt);

first$.inject(second$).inject(first$);
```

This is a bit lower level primitive than a DataFlowNode, which out of the box supports multiple output Observables. A Stream supports only one because a Stream **is** an Rx.Observable.

**Comment by staltz** [comment]
Follow the [gitter discussion here](https://gitter.im/staltz/cycle?at=551e97171f582983259f2b13).

**Comment by staltz** [comment]
MVUI architecture would probably look like this:

```javascript
var name$ = Cycle.createStream(function model(changeName$) {
  return changeName$.startWith('');
});

var vtree$ = Cycle.createStream(function view(name$) {
  return name$.map(function (name) {
    return h('div', [
      h('label', 'Name:'),
      h('input.myinput', {attributes: {type: 'text'}}),
      h('hr'),
      h('h1', 'Hello ' + name)
    ]);
  });
});

//var user = Cycle.createDOMUser('.js-container');

var interactions$ = Cycle.createStream(function user(vtree$) {
  return Cycle.render(vtree$, '.js-container').getInteractions$();
});

var changeName$ = Cycle.createStream(function intent(interactions$) {
  return interactions$.filter('.myinput', 'input').map(function (ev) {
    return ev.target.value;
  });
});

interactions$.inject(vtree$).inject(name$).inject(changeName$).inject(interactions$);
```

**Comment by chillitom** [comment]
How have you resisted coining the acronym MUVI?

**Comment by staltz** [comment]
:D 
Well, actually when naming Cycle, I first considered the name "Muovi", which in finnish means "Plastic", to refer to the framework's flexibility (when it comes to composing DataFlowNodes and functions). But Cycle sounds cooler. Also "MVUI" keeps the order correct.

**Comment by ivan-kleshnin** [comment]
Feels like the number of `inject` calls will be huge. Not sure I'm see any benefits of this.

> No .get('foo$'). They are annoying.

Couldn't that `.get('foo$')` be removed by upcoming Proxy objects? 

> Less concepts to learn. Not necessary to learn DataFlowNode/Source/Sink, just Cycle Stream, which is a subclass of Rx.Observable.

I liked that concepts because they help to structure your app.  
With only Streams it's becoming very low-level. Just like Rx. At least from the first sight.

> Less framework code. Easier to maintain and also less kilobytes delivered.

It was very small comparing to React. A few days ago you said, that kb optimization shouldn't be considered at this stage at all :wink:

On the other hand, I agree that `createModel` / `createIntent` along with `dataSource` /  `dataSink` seems artificial because they are very lean in Cycle.

**Comment by staltz** [comment]
@ivan-kleshnin I'll start making this issue on a branch, not on master, so you can see how it will evolve. The main motivation for this is to keep the concepts more "clean". Currently, Cycle "Views" are _both_  a "function" (i.e. a transformation from input to output) and an object. With this rewrite, Views become simply a function. Objects would be only Streams. Getting rid of `.get('foo$')` is rather important, unless we wait for a year (or years?) until Proxy is implemented in 95% of the browsers. It isn't currently well supported in any browser. Proxy also cannot be polyfilled.

But I'll do work on a branch and make some examples to give some idea how this will be.

**Comment by staltz** [comment]
This is the branch https://github.com/staltz/cycle/tree/streams and the first commit https://github.com/staltz/cycle/commit/703050925bf09a34b509dc145d07f027d0e762bd

**Comment by ivan-kleshnin** [comment]
Thank you. I will track the progress.

**Comment by gaearon** [comment]
As someone who observes Cycle from afar but never got deep into it, I find this API as more beginner-friendly because it seems to have less primitives. This is especially important in a framework like Cycle that claims to be more “fundamentally” sane. I don't know if it makes sense for Cycle, but you can always build higher-level abstractions on top if you really need them.

**Comment by ivan-kleshnin** [comment]
> I don't know if it makes sense for Cycle, but you can always build higher-level abstractions on top if you really need them.

Ability to build higher level abstractions is among the most important metrics of quality. 
So it definitely makes sense for Cycle just as for any other framework. React chose Component as main building block and it kinda failed because of extra complexity. Component == State + Control + Render + Magic. This is well-known God object antipattern, just veiled for unaware developer. Now we're promoting high-level component concept but that's still just kinda ugly workaround because each component still brings extra complexity and a lot of unused stuff in every instance. Main building block should be concerned about DOM. That's for sure.

**Comment by staltz** [comment]
Yes, spot on (what both said). I really like with this new API that the building blocks are just: functions and streams.

**Comment by staltz** [comment]
Here is a simple JavaScript technique for grouping related streams together: 

```javascript
let intent = (function () {
  let removeClicks$ = Cycle.createStream(interactions$ =>
    interactions$.choose('.remove-btn', 'click')
  );
  let stop$ = removeClicks$.map(() => 'stop');
  let remove$ = removeClicks$.map(() => 'remove').delay(500);

  return {
    stop$,
    remove$,
    inject(interactions$) {
      removeClicks$.inject(interactions$);
      return interactions$;
    }
  };
})();
```

**Comment by ivan-kleshnin** [comment]
@staltz :thumbsup: that looks good

**Comment by danyx23** [comment]
Like it a lot, minimizing the API surface is definitely a good idea. Will play with your branch next week.

On a sidenote, may I suggest to pronounce the observable denoting dollar sign as a plural s? As in, name the variable removeClick$ and pronounce it as removeClicks. Because you should always think of an observable as a source of multiple items anyhow.

For my own personal preference I would also replace let with const where possible (=almost everywhere).

Great work, looking forward to playing with it!

**Comment by ivan-kleshnin** [comment]
@danyx23 what's the reason with replacing `let` with `const`?
It gives nothing:

Node:
```javascript
> const x = 2
undefined
> x = 3
3
> x
3 

> const y = []
undefined
> y.push(2)
1
> y
[ 2 ]
> 

```

**Comment by ivan-kleshnin** [comment]
@danyx23 what's the benefit of `const`? The only thing it does: prevent redeclaration of variable. Only in browser. Node completely ignores it (not aware how Io.js behaves). It does not prevents you from variable mutation.

**Comment by danyx23** [comment]
const communicates to the reader that this is a single time assignment and will not be/is not intended to be overwritten. True, atm it is more about intent than a hard constraint in several cases, but it still is a valuable tool IMHO to communicate this intent.

**Comment by ivan-kleshnin** [comment]
I think the sanest approach is to treat all variables as immutable. I try to never use `[].push` for example.
So I don't see any additional semantics that `const` would add above `let`. I just treat `let` as declaration of variable that should be immutable (and probably be when we'll get macros in JS).

**Comment by danyx23** [comment]
Yes, immutable vars are a good idea. I feel const is a bit more expressive then let in that regard. It's more functionalish. In haskell and f# let is actually more like const :). But as I said, it's a personal preference. How do you feel about the $ as a plural s?

**Comment by ivan-kleshnin** [comment]
```In haskell and f# let is actually more like const :)```

Exactly, that's why I pretend to believe that JS should have same variable declaration statements.

```
How do you feel about the $ as a plural s?
```

We have at least 5 different cases: `item$`, `items$`, `changeItem$`, `changeItems$` and `interactions$`. All 5 mean different things. You proposal is about pronounciation, right? I don't get how you want to pronounce `items$` (itemss?). I read it as "stream of item[s]" in my mind.

**Comment by ivan-kleshnin** [comment]
@staltz I would still suggest against `stream`. How to distinguish between var `stream` and function `stream`? It's typical to use noun as function name only for factories. And it's conventional to capsulate factory name in that case.

**Comment by ivan-kleshnin** [comment]
Compared source code before and after. Pretty shocked how clean it is now :fearful:

**Comment by staltz** [comment]
Very valid points about the naming issue with stream. I'll definitely rethink this. Maybe it should stay as `createStream()` or maybe it should be capitalized `Stream()`, but the latter I imagine will be misused as a constructor: `new Stream()`.

> though I feel some middleware layer between Cycle and App will reappear in a while.
True, in some cases examples with the new Stream API had more lines of code than previously. Maybe we are creating additional boilerplate here. But at least we don't need to settle on that middleware yet, it can come later without bringing breaking changes.

**Comment by staltz** [comment]
As mentioned in the Gitter chat, with this new API for Cycle, now you don't need to have all moving parts being a Stream. To close the cycle, you need only one Stream, the rest can be Observables. Here is the README example with that technique:

```javascript
let name$ = Cycle.createStream(function model(changeName$) {
  return Rx.Observable.just('').merge(changeName$);
});

let vtree$ = name$.map(name =>
    h('div', [
      h('label', 'Name:'),
      h('input.field', {attributes: {type: 'text'}}),
      h('h1.header', `Hello ${name}`)
    ])
);

let interactions$ = Cycle.render(vtree$, '.js-container').interactions$;

let changeName$ = interactions$.choose('.field', 'input').map(ev => ev.target.value);

name$.inject(changeName$);
```

It still works to make all of them Cycle streams, and that might be useful to have all consistently injectable. But it's good if that decision is left for the developer.

**Comment by matthewwithanm** [comment]
> but the latter I imagine will be misused as a constructor: new Stream().

You could always guard against that with an `instanceof` check. Factory capitalization is pretty idiomatic I think.

**Comment by staltz** [comment]
Renaming not happening.
Rationale: if name size is a problem, you can use ES6 rename on import. And maybe also destructuring import might help so you call createStream() instead of Cycle.createStream(). And createStream() alone isn't that much worse than Cycle.stream(), but stream() alone is pretty bad. and createStream() is on par with other well known idioms in other JS frameworks

**Comment by staltz** [comment]
Merged into master
